"""
This module contains the `PolarizabilityTrace` class, which is a post-processing
tool for DFTB+ simulation results. It is responsible for parsing the
`detailed.out` files, extracting the static polarizability tensor, and
computing its trace. The results are then aggregated into a structured
CSV file for further analysis.
"""

import os
import numpy as np
import pandas as pd
import multiprocessing
from joblib import Parallel, delayed
from polygraphpy.core.simulator import Simulator
from tqdm import tqdm

class PolarizabilityTrace(Simulator):
    """Computes and saves the polarizability trace from DFTB+ output files.

    This class provides the functionality to parse the `detailed.out` files
    generated by DFTB+, extract the 3x3 polarizability tensor, and compute
    its trace (average polarizability). It processes multiple simulation
    directories in parallel and compiles the results into a single CSV dataset.

    :param molecules_dir: Directory containing the individual molecule job folders.
                          Defaults to 'polygraphpy/data/molecules'.
    :type molecules_dir: str, optional
    """
    
    def __init__(self, molecules_dir: str = 'polygraphpy/data/molecules'):
        """Initializes the PolarizabilityTrace processor.
        """
        super().__init__()
        self.molecules_dir = molecules_dir
    
    def prepare_input(self, input_data: str) -> None:
        """This method is not implemented in `PolarizabilityTrace`.

        Input files for this class are the DFTB+ output files, which are
        generated by a preceding simulation step.

        :raises NotImplementedError: Always, as this method is not intended for use here.
        """
        raise NotImplementedError("Input preparation not required for trace computation.")
    
    def read_polarizability(self, file_path: str) -> np.ndarray:
        """Reads the electric polarizability tensor from a `detailed.out` file.

        The method searches for the "Electric polarisability (a.u.)" section
        and extracts the 3x3 matrix that follows.

        :param file_path: The full path to the `detailed.out` file.
        :type file_path: str
        :return: A 3x3 NumPy array of the polarizability tensor, or None if parsing fails.
        :rtype: np.ndarray or None
        """
        polarizability = []
        try:
            with open(file_path, 'r') as f:
                lines = f.readlines()
                for i, line in enumerate(lines):
                    if "Electric polarisability (a.u.)" in line:
                        for j in range(i + 1, i + 4):
                            values = [float(x) for x in lines[j].split() if x]
                            polarizability.append(values)
                        break
            if len(polarizability) == 3:
                return np.array(polarizability)
            else:
                print(f"Warning: Could not parse polarizability in {file_path}")
                return None
        except Exception as e:
            print(f"Error reading {file_path}: {e}")
            return None
    
    def compute_trace(self, matrix: np.ndarray) -> tuple:
        """Computes the trace and diagonal elements of a 3x3 matrix.

        The trace is calculated as the average of the diagonal elements.

        :param matrix: The 3x3 polarizability tensor.
        :type matrix: np.ndarray
        :return: A tuple containing the diagonal elements (xx, yy, zz) and the trace.
                 Returns (None, None, None, None) if the input is invalid.
        :rtype: tuple
        """
        if matrix is not None and matrix.shape == (3, 3):
            xx = matrix[0, 0]
            yy = matrix[1, 1]
            zz = matrix[2, 2]
            trace = np.trace(matrix) / 3
            return xx, yy, zz, trace
        return None, None, None, None
    
    def write_trace_file(self, subfolder_path: str, xx: float, yy: float, zz: float, trace: float) -> None:
        """Writes the computed trace result to a `trace.txt` file.

        This file serves as a local record of the computed polarizability
        for a single molecule.

        :param subfolder_path: The path to the molecule's job directory.
        :type subfolder_path: str
        :param xx: The polarizability component along the x-axis.
        :type xx: float
        :param yy: The polarizability component along the y-axis.
        :type yy: float
        :param zz: The polarizability component along the z-axis.
        :type zz: float
        :param trace: The average polarizability (trace/3).
        :type trace: float
        :return: None
        :rtype: None
        """
        output_file = os.path.join(subfolder_path, "trace.txt")
        try:
            with open(output_file, 'w') as f:
                f.write("File Path, xx, yy, zz, Polarizability Trace (a.u.)\n")
                rel_path = os.path.basename(subfolder_path) + "/detailed.out"
                f.write(f"{rel_path}, {xx:.6f}, {yy:.6f}, {zz:.6f}, {trace:.6f}\n")
        except Exception as e:
            print(f"Error writing to {output_file}: {e}")
    
    def process_subfolder(self, subfolder_path: str, root_folder: str) -> list:
        """Processes the `detailed.out` file within a single subfolder.

        This method encapsulates the entire post-processing workflow for one
        molecule, including reading, computing the trace, and writing the
        results to a file. It also extracts molecule-specific metadata from
        the folder name.

        :param subfolder_path: The path to the specific molecule's job directory.
        :type subfolder_path: str
        :param root_folder: The root directory where all jobs are stored.
        :type root_folder: str
        :return: A list containing a single tuple of results if successful, otherwise an empty list.
        :rtype: list
        """
        results = []
        for file in os.listdir(subfolder_path):
            if file == "detailed.out":
                file_path = os.path.join(subfolder_path, file)
                polarizability_matrix = self.read_polarizability(file_path)
                if polarizability_matrix is not None:
                    xx, yy, zz, trace = self.compute_trace(polarizability_matrix)
                    if trace is not None:
                        self.write_trace_file(subfolder_path, xx, yy, zz, trace)
                        rel_path = os.path.relpath(file_path, root_folder)
                        # Extract chain_size and id from subfolder name
                        folder_name = os.path.basename(subfolder_path)
                        chain_size = None
                        mol_id_A = None
                        mol_id_B = None
                        if folder_name.startswith('homopoly_'):
                            chain_size_match = pd.Series([folder_name]).str.extract(r'homopoly_\d+_chain_(\d+)')
                            chain_size = int(chain_size_match[0][0]) if not chain_size_match.empty else None
                            id_match = pd.Series([folder_name]).str.extract(r'homopoly_(\d+)_chain_\d+')
                            mol_id_A = int(id_match[0][0]) if not id_match.empty else None
                            type = 'homopoly'
                        elif folder_name.startswith('monomer_'):
                            chain_size = 0
                            id_match = pd.Series([folder_name]).str.extract(r'monomer_(\d+)')
                            mol_id_A = int(id_match[0][0]) if not id_match.empty else None
                            type = 'monomer'
                        else:
                            chain_size_match = pd.Series([folder_name]).str.extract(r'copoly_\d+_\d+_chain_(\d+)')
                            chain_size = int(chain_size_match[0][0]) if not chain_size_match.empty else None
                            id_match = pd.Series([folder_name]).str.extract(r'copoly_(\d+)_(\d+)_chain_\d+')
                            mol_id_A = int(id_match[0][0]) if not id_match.empty else None
                            mol_id_B = int(id_match[1][0]) if not id_match.empty else None
                            type = 'copoly'
                        results.append((rel_path, xx, yy, zz, trace, chain_size, mol_id_A, mol_id_B, type))
        return results
    
    def run(self, input_csv: str) -> list:
        """Processes all subfolders in parallel to compute traces and create a dataset.

        This is the main public method. It finds all subfolders containing
        DFTB+ output, runs the `process_subfolder` method on each in parallel,
        and then compiles the results into a pandas DataFrame. This DataFrame
        is merged with the original input CSV to create a comprehensive
        polarizability dataset, which is then saved to a new CSV file.

        :param input_csv: Path to the original input CSV file containing molecule SMILES.
        :type input_csv: str
        :return: A list of tuples, where each tuple contains the computed
                 polarizability data for a single molecule.
        :rtype: list
        """
        if not os.path.exists(self.molecules_dir):
            print(f"Error: The folder '{self.molecules_dir}' does not exist.")
            return []
        
        subfolders = [os.path.join(self.molecules_dir, d) for d in os.listdir(self.molecules_dir)
                      if os.path.isdir(os.path.join(self.molecules_dir, d))]
        
        num_cores = multiprocessing.cpu_count()
        results = Parallel(n_jobs=num_cores)(
            delayed(self.process_subfolder)(subfolder, self.molecules_dir) for subfolder in tqdm(subfolders)
        )
        
        trace_results = [item for sublist in results for item in sublist]
        if not trace_results:
            print("No valid results to process.")
            return []

        # Create polarizability dataset
        df_polarizability = pd.DataFrame(trace_results, columns=['file_path', 'xx', 'yy', 'zz', 
                                                                 'static_polarizability', 'chain_size', 'id_A', 'id_B', 'type'])
        # Filter out rows where id or chain_size could not be extracted
        df_polarizability = df_polarizability.dropna(subset=['id_A', 'chain_size'])
        if df_polarizability.empty:
            print("Error: No valid IDs or chain sizes extracted from file paths.")
            return trace_results
        df_polarizability['id_A'] = df_polarizability['id_A'].astype(int)

        df_input = pd.read_csv(input_csv)

        if not df_polarizability['id_B'].isnull().all():
            df_input = df_input[['id', 'smiles']]
            df_polarizability['id_B'] = df_polarizability['id_B'].astype(int)

            df_polarizability = df_polarizability.merge(df_input.rename(columns={'id': 'id_A', 
                                                                                 'smiles': 'smiles_A',}), on=['id_A'], how='left')
            df_polarizability = df_polarizability.merge(df_input.rename(columns={'id': 'id_B', 
                                                                                 'smiles': 'smiles_B',}), on=['id_B'], how='left')
            aux = '_copoly'
        else:
            df_input = df_input[['id', 'smiles']]
            df_polarizability['chain_size'] = df_polarizability['chain_size'].astype(int)
            df_polarizability = df_polarizability.merge(df_input.rename(columns={'id': 'id_A', 
                                                                                 'smiles': 'smiles_A',}), on=['id_A'], how='left')
            df_polarizability['smiles_B'] = None
            aux = ''
        
        desired_columns = ['id_A', 'id_B', 'smiles_A', 'smiles_B', 'chain_size',
                           'xx', 'yy', 'zz', 'static_polarizability', 'type']

        available_columns = [col for col in desired_columns if col in df_polarizability.columns]
        df_polarizability = df_polarizability[available_columns]

        df_polarizability.to_csv(f'polygraphpy/data/polarizability_data{aux}.csv', index=False)

        return trace_results
    
    def process_output(self, input_csv: str) -> list:
        """Runs the polarizability trace computation and returns the results.

        This method serves as a wrapper for the `run` method, adhering to the
        `Simulator` interface.

        :param input_csv: Path to the original input CSV file.
        :type input_csv: str
        :return: A list of tuples containing the computed polarizability data.
        :rtype: list
        """
        return self.run(input_csv)